name: anaMamiTools
channels:
  - conda-forge
dependencies:
  - python>=3.0,<4.0
  - jupyterlab>=2.0,<3.0
  - numpy
  - pandas
  - matplotlib=3.3.1
  - scipy
  - tqdm
  - pyqt
  - scikit-image
  - pip
  - pip:
    - succolib
